#![doc = include_str!("../README.md")]
#![warn(missing_docs)]
// The raw igraph constants (e.g. `igraph_neimode_t_IGRAPH_OUT`) are matched upon.
#![allow(non_upper_case_globals)]

/// Raw FFI bindings to the igraph C library, generated by `bindgen` at build
/// time from the installed headers.
///
/// Everything here is re-exported at the crate root as well, so that
/// `igraph::igraph_t` and `igraph::ffi::igraph_t` are the same type. The
/// Rusty API is built *on top of these very types*: e.g. [`Graph`] is an
/// alias of [`igraph_t`] enriched with safe methods, and owned
/// types such as [`VectorInt`](crate::vector::VectorInt) free their memory on drop.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    missing_docs,
    dead_code,
    unsafe_op_in_unsafe_fn,
    clippy::all
)]
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}
#[doc(no_inline)]
pub use ffi::*;

pub mod bitset;
pub mod constants;
pub mod error;
pub mod graph;
pub mod list;
pub mod matrix;
pub mod rng;
pub mod selector;
pub mod strvector;
pub mod vector;

pub mod adjlist;
pub mod attributes;
pub mod bipartite;
pub mod centrality;
pub mod cliques;
pub mod cocitation;
pub mod community;
pub mod components;
pub mod constructors;
pub mod conversion;
pub mod cycles;
pub mod flow;
pub mod foreign;
pub mod games;
pub mod isomorphism;
pub mod layout;
pub mod linalg;
pub mod misc;
pub mod mixing;
pub mod operators;
pub mod paths;
pub mod structural;
pub mod visitor;

pub mod tutorial;

pub use error::{Error, ErrorKind, Result};
pub use graph::{EdgeId, Graph, VertexId};

/// The most commonly used types, traits and enums: `use igraph::prelude::*;`.
pub mod prelude {
    pub use crate::bitset::{Bitset, BitsetList};
    pub use crate::constants::*;
    pub use crate::error::{Error, ErrorKind, Result};
    pub use crate::graph::{EdgeId, Graph, VertexId};
    pub use crate::list::{GraphList, MatrixList, VectorIntList, VectorList};
    pub use crate::matrix::{Matrix, MatrixBool, MatrixChar, MatrixComplex, MatrixInt};
    pub use crate::rng::{self, Rng, RngType};
    pub use crate::selector::{EdgeSelector, VertexSelector};
    pub use crate::strvector::StrVector;
    pub use crate::vector::{Vector, VectorBool, VectorChar, VectorComplex, VectorInt};
}
